// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY9Y4jb9o_qn_BH-YsLIyTH5LOy_M10uQ',
    appId: '1:545877331566:web:eebb223458d5d5f857a07f',
    messagingSenderId: '545877331566',
    projectId: 'foodshop-b4cb8',
    authDomain: 'foodshop-b4cb8.firebaseapp.com',
    storageBucket: 'foodshop-b4cb8.firebasestorage.app',
    measurementId: 'G-6ZT0P942MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTDGCBET1LM0_X4cIoyMslThOWQojrDw',
    appId: '1:545877331566:android:d9885080b8edcdb557a07f',
    messagingSenderId: '545877331566',
    projectId: 'foodshop-b4cb8',
    storageBucket: 'foodshop-b4cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5281T0GbJlKDnyWsh8cKOrFVPYqWNAs',
    appId: '1:545877331566:ios:07a39f6934338a0857a07f',
    messagingSenderId: '545877331566',
    projectId: 'foodshop-b4cb8',
    storageBucket: 'foodshop-b4cb8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC5281T0GbJlKDnyWsh8cKOrFVPYqWNAs',
    appId: '1:545877331566:ios:07a39f6934338a0857a07f',
    messagingSenderId: '545877331566',
    projectId: 'foodshop-b4cb8',
    storageBucket: 'foodshop-b4cb8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY9Y4jb9o_qn_BH-YsLIyTH5LOy_M10uQ',
    appId: '1:545877331566:web:2bda15767952f39157a07f',
    messagingSenderId: '545877331566',
    projectId: 'foodshop-b4cb8',
    authDomain: 'foodshop-b4cb8.firebaseapp.com',
    storageBucket: 'foodshop-b4cb8.firebasestorage.app',
    measurementId: 'G-GN0FG8EBJ6',
  );
}